on:
  push:
    tags:
      - '*'

jobs:
  build_python:
    uses: ./.github/workflows/build-wheels.yml

  publish:
    needs: build_python
    permissions:
      id-token: write
    uses: ./.github/workflows/publish.yml
